/* 
 Copyright (c) 2011 initials. All rights reserved.
 */

#define kViewCredits @"kViewCredits"
#define kViewStats @"kViewStats"
#define kUnlockAllWarehouseLevels   @"kUnlockAllWarehouseLevels"     
#define k3CapWarehouse   @"k3CapWarehouse"
#define kUnlockAllFactoryLevels   @"kUnlockAllFactoryLevels"     
#define k3CapFactory   @"k3CapFactory"     
#define kUnlockAllManagementLevels   @"kUnlockAllManagementLevels"     
#define k3CapManagement   @"k3CapManagement"     
#define k108Caps  @"k108Caps"
#define khcUnlockAllWarehouseLevels   @"khcUnlockAllWarehouseLevels"     
#define khc3CapWarehouse   @"khc3CapWarehouse"
#define khcUnlockAllFactoryLevels   @"khcUnlockAllFactoryLevels"     
#define khc3CapFactory   @"khc3CapFactory"     
#define khcUnlockAllManagementLevels   @"khcUnlockAllManagementLevels"     
#define khc3CapManagement   @"khc3CapManagement"     
#define khc108Caps  @"khc108Caps"
#define kTalkToAllEmployees @"kTalkToAllEmployees"
#define kTalkToAndre @"kTalkToAndre"
#define kTalkToAllEmployeesHardcore @"kTalkToAllEmployeesHardcore"
#define kTalkToAndreHardcore @"kTalkToAndreHardcore"
#define kFactoryOwner @"kFactoryOwner"